export const APPLY_INITIAL_RAIN = "APPLY_INITIAL_RAIN";
export const APPLY_YEARLY_RAIN = "APPLY_YEARLY_RAIN";
export const APPLY_SEASONS_RAIN = "APPLY_SEASONS_RAIN";
export const ADVANCE_SEASON = "ADVANCE_SEASON";
export const INCREASE_MOISTURE = "INCREASE_MOISTURE";
export const DECREASE_MOISTURE = "DECREASE_MOISTURE";

export const SELECT_SQUARE = "SELECT_SQUARE";
