{
    "name": "@nui/platform",
    "version": "10.2.198",
    "description": "modern web platform",
    "private": true,
    "author": "RFx team <ecommrfxall@nordstrom.com>",
    "engines": {
        "node": ">=8.6.0",
        "npm": ">=6.0.0"
    },
    "repository": {
        "type": "git",
        "url": "ssh://git@git.nordstrom.net/nui/platform.git"
    },
    "scripts": {
        "build": "npm run build:server && node tasks/build-process-entry",
        "build:analyze": "npm run build:production analyze",
        "build:server": "babel -d dist/ src/ --copy-files",
        "build:production": "NODE_ENV=\"production\" npm run build:server && node tasks/build-process-entry production",
        "dependencies": "node tasks/dependency-manager/dependency-manager.js",
        "lint": "eslint .",
        "noob": "./install && npm run build && npm run start",
        "set-subdependency": "node tasks/set-subdependency",
        "start": "node --inspect dist --environment=development",
        "start:integration": "NODE_ENV=\"production\" node dist --environment=integration",
        "start:production": "NODE_ENV=\"production\" node dist --environment=production",
        "start:production:serviceworker": "BROWSER_ENV=\"tls\" NODE_ENV=\"production\" node dist/index --environment=production & NODE_ENV=\"production\" node tasks/service-worker-environment",
        "test": "mocha",
        "upgrade": "node tasks/upgrade.js"
    },
    "dependencies": {
        "@babel/cli": "7.0.0-beta.34",
        "@babel/core": "7.0.0-beta.34",
        "@babel/preset-env": "7.0.0-beta.34",
        "@babel/preset-react": "7.0.0-beta.34",
        "@babel/preset-stage-0": "7.0.0-beta.34",
        "@babel/runtime": "7.0.0-beta.34",
        "@nui/babel-configuration": "^2.1.4",
        "@nui/state-environment": "^1.6.12",
        "@nui/vendor-webpack-dll-debug": "^3.0.0-25427331",
        "@nui/vendor-webpack-dll-debug-es5": "^3.0.0-25427346",
        "@nui/vendor-webpack-dll-debug-node": "^3.0.0-25422897",
        "@nui/vendor-webpack-dll-production": "^3.0.0-25422902",
        "@nui/vendor-webpack-dll-production-es5": "^3.0.0-25422907",
        "@nui/vendor-webpack-dll-production-node": "^3.0.0-25422913",
        "babel-loader": "8.0.0-beta.2",
        "boom": "^7.2.0",
        "caniuse-lite": "^1.0.30000824",
        "child-process-promise": "^2.2.1",
        "concat": "^1.0.3",
        "cors": "^2.8.4",
        "dnscache": "^1.0.1",
        "electrode-confippet": "^1.5.0",
        "electrode-server": "^1.5.0",
        "fastify": "^1.2.1",
        "find": "^0.2.9",
        "fs-extra": "^5.0.0",
        "good": "^7.3.0",
        "good-console": "^6.2.0",
        "good-file": "^6.0.1",
        "good-http": "^6.1.1",
        "good-squeeze": "^5.0.0",
        "hot-shots": "^5.4.0",
        "inert": "^4.2.1",
        "jsrsasign": "^8.0.12",
        "lodash.camelcase": "^4.3.0",
        "lodash.kebabcase": "^4.1.1",
        "minimist": "^1.2.0",
        "mkdirp-promise": "^5.0.1",
        "mustache": "^2.3.0",
        "pascal-case": "^2.0.1",
        "react": "^16.3.1",
        "react-dom": "^16.3.1",
        "rmfr": "^2.0.0",
        "stable": "^0.1.8",
        "ua-parser-js": "^0.7.17",
        "uglifyjs-webpack-plugin": "^1.0.0",
        "uuid": "^3.3.2",
        "webpack": "^4.2.0",
        "workbox-build": "^3.6.1"
    },
    "devDependencies": {
        "@babel/register": "7.0.0-beta.34",
        "@nui/eslint-config-react": "^6.0.1",
        "babel-plugin-add-module-exports": "^0.2.1",
        "chai": "^4.2.0",
        "chai-as-promised": "^7.1.1",
        "chrome-launcher": "^0.10.5",
        "cssnano": "^4.1.7",
        "eslint": "^5.10.0",
        "lodash.clonedeep": "^4.5.0",
        "mocha": "^5.2.0",
        "nock": "^10.0.4",
        "npm-merge-driver": "^2.3.5",
        "package-json": "^4.0.1",
        "postcss": "^7.0.5",
        "sinon": "^7.2.2",
        "sinon-chai": "^3.3.0",
        "uglifyjs-webpack-plugin": "^1.3.0",
        "v8-profiler-node8": "^6.0.1",
        "webpack-bundle-analyzer": "^2.13.1"
    }
}
